sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: 0qjGcWFRukI3yprrAeSH+L1bZRVF0dx52HbbPARR/GpvXp+A4u67G8Q4n/rH8myri+ftU9niS2BSphBJ1eyYVRq9VWpRTyQJuhkJ5f+JI1nTh763nhpRPb1fCuohFfjCvlEkwoXJKaVfCkHkHgnpXxzTbz2UdHLjo9FiBBsN2Aina6k/ZemrsUwFMsoKB0fypsITWFyHlkMbaivh82FZuR8TjXV7apDWx/Z0Yxfelip+E8caF+5i0w9NNVHhsMNWaMqnl7Q0pZOkP5mI0/zJmoQpTrTaKp7EVkUChuV2sxMYcJIxlj5ca4uBzSYLvhPVdymvhITqdu+VEItWYVTaV/rowiuYtDi9byOpsn4QhwGQqPsyRwIJuES1g4JDF4naLYsW9uNLwrPMGWLbxOiEiMgu8excPu/BJMJxH7qP9Xem8eil50ovoTncKmaR2Y0Nj9o32u35mtd5niANfjgKsEIwAz7jkE5UV3nw5LsfjRn9kfJ0QrGV6EQZ+cX72ED/gdk0iT2ahOSGrn/Qb8sc18dipN98cB1t2MAGTBpWiW+zNLoyG+UWe7eUCQs1k2wvyTm7u2TDs3Oq2KuxLNg3uwUKMl4zCfqPVXReyAPYEyBOpZyATRhotKLDhIK57yjgLWVuUGBmsuCEFzx1aOYnviYk5NMmJNNXCqE4eMIhJ74=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/A-Modern-Chronicle---Volume-01_5374
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy